name: compleat_mobile
description: Com-Pleat Inventory Management Mobile App
publish_to: 'none'
version: 1.0.11+12

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  url_launcher: ^6.2.5
  dropdown_search: ^5.0.6
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.1
  intl: ^0.18.1
  package_info_plus: ^4.2.0
  dio: ^5.4.0
  android_intent_plus: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-compleat.jpg
    - assets/images/logo-servair.jpg
    - assets/images/ComPleat_Logo_Mark.png
